[package]
name = "waku-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
libp2p = { workspace = true, features = ["gossipsub", "macros"] }
prost = "0.11.6"
strum_macros = "0.24.3"
thiserror = "1.0.38"
waku-core = { version = "0.1.0", path = "../waku-core" }
