[package]
name = "waku-message"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = { version = "4.0.17", default-features = false, features = ["std"] }
bytes = "1.3.0"
prost = "0.11.3"
